image: node:9
deploy staging:
  stage: deploy
  before_script:
  - apt-get update
  - apt-get install -y sshpass
  script:
    - export SSHPASS=$HRO_STAGING_PASSWORD 
    - sshpass -e scp -o stricthostkeychecking=no -r /builds/the-spartans/Dashboard/src/ $HRO_STAGING_USER@$HRO_STAGING_IP:$HRO_STAGING_PATH
  environment:
    name: HRO staging
  only:
  - master
