image: node:9
deploy staging:
  image: ubuntu
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y sshpass
    - sshpass -pv "$HRO_STAGING_PASSWORD" scp -r src/ $HRO_STAGING_USER@$HRO_STAGING_IP:$HRO_STAGING_PATH
  environment:
    name: HRO staging
    url: http://145.24.222.141/
  only:
  - master
