image: node:9
deploy staging:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy
  script:
    - ls -la /builds/the-spartans/Dashboard/
  environment:
    name: HRO staging
    url: http://145.24.222.141/
  only:
  - master
