image: node:9
deploy staging:
  stage: deploy
  before_script:
    - echo "skipped"
  script:
    - apt-get update
    - apt-get install -y ssh-keygen sshpass rsync
    - ssh-keygen -R $HRO_STAGING_IP
    - sshpass -p ‘$HRO_STAGING_PASSWORD’ rsync --progress -avzr -e ssh -o StrictHostKeyChecking=no /builds/the-spartans/Dashboard/src/ $HRO_STAGING_USER@$HRO_STAGING_IP:$HRO_STAGING_PATH
  environment:
    name: HRO staging
    url: http://145.24.222.141/
  only:
  - master
