deploy staging:
  image: mwienk/docker-lftp
  stage: deploy
  script:
    - lftp -e "mirror -R src/ $HRO_STAGING_PATH" -u $HRO_STAGING_IP,$HRO_STAGING_PASSWORD $HRO_STAGING_IP 
  environment:
    name: HRO staging
    url: http://145.24.222.141/
  only:
  - master
