image: node:9
deploy staging:
  stage: deploy
  before_script:
    - echo "skipped"
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - apt-get update
    - apt-get install -y sshpass scp
    - sshpass -p $HRO_STAGING_PASSWORD scp -r /builds/the-spartans/Dashboard/src/ $HRO_STAGING_USER@$HRO_STAGING_IP:$HRO_STAGING_PATH
  environment:
    name: HRO staging
  only:
  - master
