image: node:9
before_script:
    - npm install --progress=false
cache:
  paths:
    - node_modules/
build site:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
lint: 
  stage: test
  script:
    - npm run lint
unit test:
  stage: test
  script:
    - npm run unit
deploy staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: HRO staging
    url: http://145.24.222.141/
  only:
  - master
