export const SET_TOOLBAR_TITLE = 'SET_TOOLBAR_TITLE'
export const ADD_TOOLBAR_BUTTON = 'ADD_TOOLBAR_BUTTON'
export const REMOVE_TOOLBAR_BUTTON = 'REMOVE_TOOLBAR_BUTTON'
export const SET_SNACKBAR_MESSAGE = 'SET_SNACKBAR_MESSAGE'
export default {
  SET_TOOLBAR_TITLE,
  ADD_TOOLBAR_BUTTON,
  REMOVE_TOOLBAR_BUTTON,
  SET_SNACKBAR_MESSAGE
}
