export const SET_TOOLBAR_TITLE = 'SET_TOOLBAR_TITLE'
export const ADD_TOOLBAR_BUTTON = 'ADD_TOOLBAR_BUTTON'
export const REMOVE_TOOLBAR_BUTTON = 'REMOVE_TOOLBAR_BUTTON'
export default {
  SET_TOOLBAR_TITLE,
  ADD_TOOLBAR_BUTTON,
  REMOVE_TOOLBAR_BUTTON
}
